name: Test

on:
  push:
    branches:
      - "main"
    paths:
      - "action.yml"
      - "index.js"
      - "package-lock.json"
      - "package.json"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Update
        run: |
          npm install
          npm run package
          mv ../action.yml .
          mv ../LICENSE .
          mv ../README.md .
      - name: Setup Minecraft
        id: minecraft
        uses: mcenv/setup-minecraft@dist
        with:
          version: snapshot
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: ${{ fromJson(steps.minecraft.outputs.package).javaVersion.majorVersion }}
      - name: Check Minecraft
        run: |
          echo Running Minecraft ${{ steps.minecraft.outputs.version }}.
          java -jar $MINECRAFT --help
